global:
  scrape_interval:     15s
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    static_configs:
    - targets: ['localhost:9090']
  
  # Scrape configuration for our hello world app
  - job_name: 'myapp'
    scrape_interval: 2s
    static_configs:
    - targets: ['host.docker.internal:3000'] #You may need to change this to localhost. Depends on OS.

  - job_name: 'node'
    scrape_interval: 2s
    static_configs:
    - targets: ['host.docker.internal:9100'] #You may need to change this to localhost. Depends on OS.

